### ISSUE TITLE
Implement Connected.jsx

### ISSUE THREAD

**Issue by seanquiambao** [acm-ucr/ucr-swim-website#8]
![image](https://github.com/acm-ucr/ucr-swim-website/assets/123037099/18bac8d3-42ee-49c1-898f-c763cad39194)

- Number of props: 0
- Location: Home Page
- Number of Images: 0
- React Icon: No

Description: This component includes a blue title on the top and a yellow subtitle on the bottom. 

**PATH: /src/components/home/Connected.jsx**

Example: https://github.com/acm-ucr/robosub-website/blob/dev/src/components/Subtitle.jsx

**Comment by hdave07** [comment]
<img width="600" alt="Screenshot 2024-04-11 at 7 31 08 PM" src="https://github.com/acm-ucr/ucr-swim-website/assets/139363345/dfe7f013-9d1d-4d19-98ad-3ca0bb8d2162">
